### ISSUE TITLE
[FEATURE] Pass parameters through the different raptor calls.

### ISSUE THREAD

**Issue by Irallia** [seqan/raptor#198] opened 2022-11-16 12:08 UTC
Is there a possibility to pass the parameters through the different raptor calls?
For example the fpr from `raptor build` via the index to `raptor search`?
This would avoid mistakes.

**Comment by eseiler** [comment] 2022-11-16 12:34
Duplicate of https://github.com/seqan/raptor/issues/139

**Closed by eseiler** 2022-11-16 12:34 UTC
Labels: duplicate
